// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Data;

namespace Test.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210519155120_Initialç")]
    partial class Initialç
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Test.Models.Caes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caes");
                });

            modelBuilder.Entity("Test.Models.Donos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Donos");
                });

            modelBuilder.Entity("Test.Models.ManyToMany.CaesDono", b =>
                {
                    b.Property<int>("DonosId")
                        .HasColumnType("int");

                    b.Property<int>("CaesId")
                        .HasColumnType("int");

                    b.HasKey("DonosId", "CaesId");

                    b.HasIndex("CaesId");

                    b.ToTable("CaesDono");
                });

            modelBuilder.Entity("Test.Models.ManyToMany.CaesDono", b =>
                {
                    b.HasOne("Test.Models.Caes", "Caes")
                        .WithMany("CaesDono")
                        .HasForeignKey("CaesId")
                        .IsRequired();

                    b.HasOne("Test.Models.Donos", "Donos")
                        .WithMany("CaesDono")
                        .HasForeignKey("DonosId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
